# Naikkan RAM JVM ke 4GB dan gunakan G1 Garbage Collector
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC

# Aktifkan AndroidX & Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Matikan Incremental & Build Cache untuk mencegah cache corrupt saat debugging
kotlin.incremental=false
android.enableBuildCache=false
org.gradle.parallel=false